version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "unless-stopped"
    depends_on:
      - broker
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:9092"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vehicledetection
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  producer:
    build: ./producer
    volumes:
      - ./producer/:/usr/src
    env_file:
      - ./producer/.env

  indexer:
    build: ./indexer
    volumes:
      - ./indexer/:/usr/src
    env_file:
      - ./indexer/.env

  api:
    build: ./api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"
    links:
      - mongo
      - broker
    volumes:
      - ./api/:/usr/app
    env_file:
      - ./api/.env

volumes:
  mongo-data:
  mongo-configdb:

networks:
  default:
    name: intellisite