version: "3.7"

services:
  indexer:
    build: ../indexer
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      MONGO_INITDB_ROOT_USERNAME: vehicledetection
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_HOST: mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vehicledetection
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb:

networks:
  default:
    name: intellisite
