version: '3.7'

services:
  api:
    build: ../api
    environment:
      MONGO_INITDB_ROOT_USERNAME: vehicledetection
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_HOST: mongo
    ports:
      - "8000:8000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vehicledetection
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb:

networks:
  default:
    name: intellisite
